apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mesh-platform
  namespace: argocd

spec:
  description: Mesh Platform

  sourceRepos:
  - "https://github.com/manibratam1221/mesh-platform.git"

  destinations:
  - namespace: prod
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
