apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.name }}

spec:
  replicas: {{ .Values.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.labels.app }}

  template:

    metadata:
      labels:
        app: {{ .Values.labels.app }}
        version: {{ .Values.labels.version }}

    spec:

      containers:

      - name: {{ .Values.name }}

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:

        - containerPort: 80
