apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "mesh-service.fullname" . }}
  labels:
{{ include "mesh-service.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.labels.app }}

  template:

    metadata:
      labels:
        app: {{ .Values.labels.app }}
        version: {{ .Values.labels.version }}

    spec:
      serviceAccountName: {{ include "mesh-service.fullname" .}}
      containers:

      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
        {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
        {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 10 }}
        {{- end }}
        securityContext:{{ toYaml .Values.securityContext | nindent 10 }}
        resources:
{{ toYaml .Values.resources | nindent 12 }}
        ports:
        - containerPort: {{.Values.service.port }}
