{{- if .Values.serviceAccount.create }}

apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "mesh-service.fullname" . }}

  labels:

{{ include "mesh-service.labels" . | indent 4 }}

{{- end }}
